-- Chạy toàn bộ file này trong Supabase SQL Editor.

create table if not exists public.parking_vehicles (
  id bigint generated by default as identity primary key,
  slot text not null,
  plate text not null unique,
  driver_name text not null,
  phone text not null,
  vehicle_type text not null default 'Ô tô',
  monthly_fee bigint not null default 0 check (monthly_fee >= 0),
  month_paid boolean not null default false,
  wash_credits integer not null default 0 check (wash_credits >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.parking_washes (
  id bigint generated by default as identity primary key,
  vehicle_id bigint references public.parking_vehicles(id) on delete set null,
  plate text not null,
  work_item text not null,
  price bigint not null default 0 check (price >= 0),
  discount bigint not null default 0 check (discount >= 0),
  final_amount bigint not null default 0 check (final_amount >= 0),
  used_credit boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.parking_services (
  id bigint generated by default as identity primary key,
  vehicle_id bigint references public.parking_vehicles(id) on delete set null,
  plate text not null,
  service_name text not null,
  price bigint not null default 0 check (price >= 0),
  discount bigint not null default 0 check (discount >= 0),
  final_amount bigint not null default 0 check (final_amount >= 0),
  bonus_washes integer not null default 0 check (bonus_washes >= 0),
  note text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.parking_payments (
  id bigint generated by default as identity primary key,
  vehicle_id bigint references public.parking_vehicles(id) on delete set null,
  plate text not null,
  amount bigint not null default 0 check (amount >= 0),
  payment_type text not null default 'Tiền tháng',
  note text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists parking_washes_created_at_idx on public.parking_washes(created_at desc);
create index if not exists parking_services_created_at_idx on public.parking_services(created_at desc);
create index if not exists parking_payments_created_at_idx on public.parking_payments(created_at desc);

alter table public.parking_vehicles enable row level security;
alter table public.parking_washes enable row level security;
alter table public.parking_services enable row level security;
alter table public.parking_payments enable row level security;

create or replace function public.parking_add_vehicle(
  p_slot text,
  p_plate text,
  p_driver_name text,
  p_phone text,
  p_vehicle_type text default 'Ô tô',
  p_monthly_fee bigint default 0,
  p_month_paid boolean default false,
  p_wash_credits integer default 0
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if nullif(trim(p_slot), '') is null or nullif(trim(p_plate), '') is null
     or nullif(trim(p_driver_name), '') is null or nullif(trim(p_phone), '') is null then
    raise exception 'Vui lòng nhập đủ ô đỗ, biển số, tên và số điện thoại.';
  end if;

  insert into public.parking_vehicles (
    slot, plate, driver_name, phone, vehicle_type, monthly_fee, month_paid, wash_credits
  ) values (
    upper(trim(p_slot)), upper(trim(p_plate)), trim(p_driver_name), trim(p_phone),
    coalesce(nullif(trim(p_vehicle_type), ''), 'Ô tô'),
    greatest(coalesce(p_monthly_fee, 0), 0),
    coalesce(p_month_paid, false),
    greatest(coalesce(p_wash_credits, 0), 0)
  );
end;
$$;

create or replace function public.parking_record_wash(
  p_vehicle_id bigint,
  p_plate text,
  p_work_item text,
  p_price bigint default 0,
  p_discount bigint default 0,
  p_used_credit boolean default false
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_credits integer;
  clean_price bigint := greatest(coalesce(p_price, 0), 0);
  clean_discount bigint;
begin
  if nullif(trim(p_plate), '') is null or nullif(trim(p_work_item), '') is null then
    raise exception 'Vui lòng chọn xe và hạng mục rửa.';
  end if;

  if coalesce(p_used_credit, false) then
    select wash_credits into current_credits
    from public.parking_vehicles
    where id = p_vehicle_id
    for update;
    if coalesce(current_credits, 0) < 1 then
      raise exception 'Xe này không còn lượt rửa miễn phí.';
    end if;
    update public.parking_vehicles set wash_credits = wash_credits - 1 where id = p_vehicle_id;
    clean_discount := clean_price;
  else
    clean_discount := least(clean_price, greatest(coalesce(p_discount, 0), 0));
  end if;

  insert into public.parking_washes (
    vehicle_id, plate, work_item, price, discount, final_amount, used_credit
  ) values (
    p_vehicle_id, upper(trim(p_plate)), trim(p_work_item), clean_price,
    clean_discount, clean_price - clean_discount, coalesce(p_used_credit, false)
  );
end;
$$;

create or replace function public.parking_collect_payment(
  p_vehicle_id bigint,
  p_amount bigint default 0,
  p_note text default ''
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_vehicle public.parking_vehicles%rowtype;
  clean_amount bigint;
begin
  select * into selected_vehicle from public.parking_vehicles where id = p_vehicle_id for update;
  if not found then raise exception 'Không tìm thấy xe.'; end if;

  clean_amount := greatest(coalesce(nullif(p_amount, 0), selected_vehicle.monthly_fee), 0);
  update public.parking_vehicles set month_paid = true where id = p_vehicle_id;
  insert into public.parking_payments (vehicle_id, plate, amount, payment_type, note)
  values (p_vehicle_id, selected_vehicle.plate, clean_amount, 'Tiền tháng', coalesce(p_note, ''));
end;
$$;

create or replace function public.parking_add_service(
  p_vehicle_id bigint,
  p_plate text,
  p_service_name text,
  p_price bigint default 0,
  p_discount bigint default 0,
  p_bonus_washes integer default 0,
  p_note text default ''
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_price bigint := greatest(coalesce(p_price, 0), 0);
  clean_discount bigint;
  clean_bonus integer := greatest(coalesce(p_bonus_washes, 0), 0);
begin
  if nullif(trim(p_plate), '') is null or nullif(trim(p_service_name), '') is null then
    raise exception 'Vui lòng chọn xe và nhập tên dịch vụ.';
  end if;

  clean_discount := least(clean_price, greatest(coalesce(p_discount, 0), 0));
  insert into public.parking_services (
    vehicle_id, plate, service_name, price, discount, final_amount, bonus_washes, note
  ) values (
    p_vehicle_id, upper(trim(p_plate)), trim(p_service_name), clean_price,
    clean_discount, clean_price - clean_discount, clean_bonus, coalesce(p_note, '')
  );

  if p_vehicle_id is not null and clean_bonus > 0 then
    update public.parking_vehicles
    set wash_credits = wash_credits + clean_bonus
    where id = p_vehicle_id;
  end if;
end;
$$;

create or replace function public.parking_toggle_paid(
  p_vehicle_id bigint,
  p_month_paid boolean
) returns void
language sql
security definer
set search_path = public
as $$
  update public.parking_vehicles
  set month_paid = coalesce(p_month_paid, false)
  where id = p_vehicle_id;
$$;

revoke all on public.parking_vehicles, public.parking_washes, public.parking_services, public.parking_payments from anon, authenticated;
grant select, insert, update, delete on public.parking_vehicles, public.parking_washes, public.parking_services, public.parking_payments to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on function public.parking_add_vehicle(text, text, text, text, text, bigint, boolean, integer) to service_role;
grant execute on function public.parking_record_wash(bigint, text, text, bigint, bigint, boolean) to service_role;
grant execute on function public.parking_collect_payment(bigint, bigint, text) to service_role;
grant execute on function public.parking_add_service(bigint, text, text, bigint, bigint, integer, text) to service_role;
grant execute on function public.parking_toggle_paid(bigint, boolean) to service_role;
